### ISSUE TITLE
Pass SCSS lint 

### ISSUE THREAD

**Issue by bertrandk** [rangle/skeletor#13]
We should probably ensure we pass our own lint rules (or change them :neckbeard:).

Here's what I've found so far:
- [ ] Use `//` comments everywhere: there are many places where we are using `/* */` (this can be relaxed since it seems reasonable for section titles)
- [ ] LeadingZero: `0.x` should be written without a leading zero as `.x`
- [ ] SelectorFormat: Selector `xxxx__yyy--zzz` should be written in lowercase with hyphens :-1: 
- [ ] QualifyingElement: Avoid qualifying attribute selectors with an element. :confounded: 
- [ ] UnnecessaryMantissa: `x.0rem` should be written without the mantissa as `xrem`

**Comment by winkerVSbecks** [comment]
Last I checked there were no linting errors. Are you sure you are using the right file?

> Use // comments everywhere: there are many places where we are using /* */ (this can be relaxed since it seems reasonable for section titles)

This is disabled

> LeadingZero: 0.x should be written without a leading zero as .x

again disabled. My preference is `0.x`

> SelectorFormat: Selector xxxx__yyy--zzz should be written in lowercase with hyphens :-1:

we're using hyphenated_BEM (https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#selectorformat)

> QualifyingElement: Avoid qualifying attribute selectors with an element. :confounded:

```yaml
  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: false
    allow_element_with_id: false
```

> UnnecessaryMantissa: x.0rem should be written without the mantissa as xrem

again disabled, sometimes 5.0rem is nice. 


We should enable final new line:

```yaml
FinalNewline:
    enabled: true
    present: true
```
